from __future__ import annotations

from typing import Dict, List, Optional

DEFAULT_FONT_PRESET_ID = "neon_block"
DEFAULT_TEMPLATE_ID = "neon_panorama"
DEFAULT_STYLE_PRESET_ID = "neon_core"

FONT_PRESETS: Dict[str, Dict[str, object]] = {
    "neon_block": {
        "name": "Neon Block",
        "bar_full": "█",
        "bar_empty": "░",
        "sparkline": "▁▂▃▄▅▆▇█",
        "spectrum": [" ", "▂", "▃", "▄", "▅", "▆", "▇", "█"],
        "arrow_up": "▲",
        "arrow_down": "▼",
        "image_chars": "@%#*+=-:. ",
        "stream_chars": "01",
    },
    "amber_ascii": {
        "name": "Amber Terminal",
        "bar_full": "#",
        "bar_empty": ".",
        "sparkline": " .:-=+*#",
        "spectrum": [" ", ".", ":", "-", "=", "+", "*", "#"],
        "arrow_up": "^",
        "arrow_down": "v",
        "image_chars": "$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/|()1{}[]?-_+~<>i!lI;:,\"^`'. ",
        "stream_chars": "XO.",
    },
    "ice_thin": {
        "name": "Ice Thin",
        "bar_full": "■",
        "bar_empty": "·",
        "sparkline": " ·.:=+*#",
        "spectrum": [" ", "·", ".", ":", "=", "+", "*", "#"],
        "arrow_up": "↑",
        "arrow_down": "↓",
        "image_chars": "@%#*+=-:. ",
        "stream_chars": "·:*-",
    },
    "mono_dot": {
        "name": "Mono Dot",
        "bar_full": "=",
        "bar_empty": " ",
        "sparkline": " .-:=+*#",
        "spectrum": [" ", ".", "-", "=", "+", "*", "#"],
        "arrow_up": "^",
        "arrow_down": "v",
        "image_chars": "@%#*+=-:. ",
        "stream_chars": ".:-;",
    },
    "vapor_line": {
        "name": "Vapor Line",
        "bar_full": "█",
        "bar_empty": "·",
        "sparkline": " ▁▂▃▄▅▆▇█",
        "spectrum": [" ", "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"],
        "arrow_up": "▲",
        "arrow_down": "▼",
        "image_chars": " .:-=+*#%@",
        "stream_chars": "01#",
    },
    "matrix_code": {
        "name": "Matrix Code",
        "bar_full": "▓",
        "bar_empty": "░",
        "sparkline": " ░▒▓█",
        "spectrum": [" ", "░", "▒", "▓", "█"],
        "arrow_up": "↑",
        "arrow_down": "↓",
        "image_chars": "01",
        "stream_chars": "01",
    },
}

STYLE_PRESETS: Dict[str, Dict[str, object]] = {
    "neon_core": {
        "name": "Neon Core",
        "title_style": "bold",
        "title_color": "#FF00FF",
        "colors": {
            "primary": "#00FF41",
            "secondary": "#00FFFF",
            "accent": "#FFD700",
            "muted": "#66FF99",
            "warning": "#FFD700",
            "danger": "#FF3355",
            "cpu_ok": "#00FF41",
            "cpu_warn": "#FFD700",
            "cpu_crit": "#FF3355",
            "mem": "#00FFFF",
            "swap": "#FF00FF",
            "panel_cpu": "#00FF41",
            "panel_mem": "#00BFFF",
            "net_down": "#00FFFF",
            "net_up": "#FF00FF",
            "ticker": "#00FFFF",
            "badge_ok": "#00FF41",
            "badge_warn": "#FFD700",
            "badge_crit": "#FF3355",
            "stream": "#00FF41",
            "stream_accent": "#00FFFF",
            "audio_low": "#00FFFF",
            "audio_mid": "#5AA9FF",
            "audio_high": "#FF00FF",
            "time": "#FF00FF",
            "date": "#00FFFF",
        },
    },
    "amber_scan": {
        "name": "Amber Scan",
        "title_style": "bold",
        "title_color": "#FFB000",
        "colors": {
            "primary": "#FFB000",
            "secondary": "#FF8800",
            "accent": "#FFD166",
            "muted": "#FFD8A8",
            "warning": "#FF8800",
            "danger": "#FF3B3B",
            "cpu_ok": "#FFB000",
            "cpu_warn": "#FF8800",
            "cpu_crit": "#FF3B3B",
            "mem": "#FFD166",
            "swap": "#FF6A00",
            "panel_cpu": "#FFB000",
            "panel_mem": "#FF8800",
            "net_down": "#FFD166",
            "net_up": "#FF6A00",
            "ticker": "#FFD166",
            "badge_ok": "#FFB000",
            "badge_warn": "#FF8800",
            "badge_crit": "#FF3B3B",
            "stream": "#FFB000",
            "stream_accent": "#FFD166",
            "audio_low": "#FFD166",
            "audio_mid": "#FF9F1C",
            "audio_high": "#FF6A00",
            "time": "#FFB000",
            "date": "#FFD166",
        },
    },
    "ice_flow": {
        "name": "Ice Flow",
        "title_style": "bold",
        "title_color": "#5EE7FF",
        "colors": {
            "primary": "#5EE7FF",
            "secondary": "#7BB5FF",
            "accent": "#A6F0FF",
            "muted": "#A8E8FF",
            "warning": "#FFD166",
            "danger": "#FF6B6B",
            "cpu_ok": "#5EE7FF",
            "cpu_warn": "#7BB5FF",
            "cpu_crit": "#FF6B6B",
            "mem": "#7BB5FF",
            "swap": "#5EE7FF",
            "panel_cpu": "#5EE7FF",
            "panel_mem": "#7BB5FF",
            "net_down": "#5EE7FF",
            "net_up": "#7BB5FF",
            "ticker": "#A6F0FF",
            "badge_ok": "#5EE7FF",
            "badge_warn": "#FFD166",
            "badge_crit": "#FF6B6B",
            "stream": "#5EE7FF",
            "stream_accent": "#A6F0FF",
            "audio_low": "#5EE7FF",
            "audio_mid": "#7BB5FF",
            "audio_high": "#A6F0FF",
            "time": "#5EE7FF",
            "date": "#7BB5FF",
        },
    },
    "mono_line": {
        "name": "Mono Line",
        "title_style": "bold",
        "title_color": "#D0D0D0",
        "colors": {
            "primary": "#D0D0D0",
            "secondary": "#A0A0A0",
            "accent": "#FFFFFF",
            "muted": "#8C8C8C",
            "warning": "#FFD700",
            "danger": "#FF5555",
            "cpu_ok": "#D0D0D0",
            "cpu_warn": "#FFD700",
            "cpu_crit": "#FF5555",
            "mem": "#A0A0A0",
            "swap": "#C0C0C0",
            "panel_cpu": "#A0A0A0",
            "panel_mem": "#8C8C8C",
            "net_down": "#C0C0C0",
            "net_up": "#FFFFFF",
            "ticker": "#C0C0C0",
            "badge_ok": "#D0D0D0",
            "badge_warn": "#FFD700",
            "badge_crit": "#FF5555",
            "stream": "#A0A0A0",
            "stream_accent": "#FFFFFF",
            "audio_low": "#A0A0A0",
            "audio_mid": "#C0C0C0",
            "audio_high": "#FFFFFF",
            "time": "#FFFFFF",
            "date": "#C0C0C0",
        },
    },
    "vapor_pulse": {
        "name": "Vapor Pulse",
        "title_style": "bold",
        "title_color": "#FF6AD5",
        "colors": {
            "primary": "#FF6AD5",
            "secondary": "#7DF9FF",
            "accent": "#B967FF",
            "muted": "#CDB4FF",
            "warning": "#FFD166",
            "danger": "#FF4D6D",
            "cpu_ok": "#7DF9FF",
            "cpu_warn": "#FFD166",
            "cpu_crit": "#FF4D6D",
            "mem": "#7DF9FF",
            "swap": "#FF6AD5",
            "panel_cpu": "#7DF9FF",
            "panel_mem": "#B967FF",
            "net_down": "#7DF9FF",
            "net_up": "#FF6AD5",
            "ticker": "#7DF9FF",
            "badge_ok": "#7DF9FF",
            "badge_warn": "#FFD166",
            "badge_crit": "#FF4D6D",
            "stream": "#FF6AD5",
            "stream_accent": "#7DF9FF",
            "audio_low": "#7DF9FF",
            "audio_mid": "#B967FF",
            "audio_high": "#FF6AD5",
            "time": "#FF6AD5",
            "date": "#7DF9FF",
        },
    },
    "aurora_wave": {
        "name": "Aurora Wave",
        "title_style": "bold",
        "title_color": "#7CFFB2",
        "colors": {
            "primary": "#7CFFB2",
            "secondary": "#4ED4FF",
            "accent": "#00FFAA",
            "muted": "#A6FFE4",
            "warning": "#FFD166",
            "danger": "#FF6B6B",
            "cpu_ok": "#7CFFB2",
            "cpu_warn": "#FFD166",
            "cpu_crit": "#FF6B6B",
            "mem": "#4ED4FF",
            "swap": "#00FFAA",
            "panel_cpu": "#7CFFB2",
            "panel_mem": "#4ED4FF",
            "net_down": "#4ED4FF",
            "net_up": "#00FFAA",
            "ticker": "#4ED4FF",
            "badge_ok": "#7CFFB2",
            "badge_warn": "#FFD166",
            "badge_crit": "#FF6B6B",
            "stream": "#7CFFB2",
            "stream_accent": "#4ED4FF",
            "audio_low": "#4ED4FF",
            "audio_mid": "#7CFFB2",
            "audio_high": "#00FFAA",
            "time": "#00FFAA",
            "date": "#4ED4FF",
        },
    },
    "ember_core": {
        "name": "Ember Core",
        "title_style": "bold",
        "title_color": "#FF6A00",
        "colors": {
            "primary": "#FF6A00",
            "secondary": "#FFB347",
            "accent": "#FF3B3B",
            "muted": "#FFD2A6",
            "warning": "#FFB347",
            "danger": "#FF3B3B",
            "cpu_ok": "#FFB347",
            "cpu_warn": "#FF6A00",
            "cpu_crit": "#FF3B3B",
            "mem": "#FFB347",
            "swap": "#FF6A00",
            "panel_cpu": "#FF6A00",
            "panel_mem": "#FFB347",
            "net_down": "#FFB347",
            "net_up": "#FF6A00",
            "ticker": "#FFB347",
            "badge_ok": "#FFB347",
            "badge_warn": "#FF6A00",
            "badge_crit": "#FF3B3B",
            "stream": "#FF6A00",
            "stream_accent": "#FFB347",
            "audio_low": "#FFB347",
            "audio_mid": "#FF6A00",
            "audio_high": "#FF3B3B",
            "time": "#FF6A00",
            "date": "#FFB347",
        },
    },
}

TEMPLATE_PRESETS: List[Dict[str, object]] = [
    {
        "id": "neon_panorama",
        "name": "Neon Panorama",
        "description": "超宽横屏信息墙，适合 1920x480 / 2560x720。",
        "screen_profile": "ultrawide",
        "recommended_resolution": "1920x480",
        "layout_class": "layout-ultrawide",
        "theme_class": "theme-neon",
        "font_preset": "neon_block",
        "style_preset": "neon_core",
        "global_scale": 1.0,
        "tags": ["ultrawide", "cyber", "dashboard"],
        "purpose_tags": ["dashboard", "monitoring"],
        "style_tags": ["neon", "cyberpunk"],
        "active_components": ["p_hardware", "p_network", "p_clock", "p_audio", "p_image"],
        "component_variants": {
            "p_hardware": "variant-dense",
            "p_network": "variant-slim",
            "p_clock": "variant-minimal",
            "p_audio": "variant-banner",
            "p_image": "variant-compact",
        },
    },
    {
        "id": "amber_console",
        "name": "Amber Console",
        "description": "复古终端风格，适合中等宽屏与低分辨率屏幕。",
        "screen_profile": "wide",
        "recommended_resolution": "1280x480",
        "layout_class": "layout-wide",
        "theme_class": "theme-amber",
        "font_preset": "amber_ascii",
        "style_preset": "amber_scan",
        "global_scale": 0.9,
        "tags": ["retro", "wide", "terminal"],
        "purpose_tags": ["terminal", "monitoring"],
        "style_tags": ["retro", "amber"],
        "active_components": ["p_hardware", "p_network", "p_clock", "p_audio", "p_image"],
        "component_variants": {
            "p_hardware": "variant-compact",
            "p_network": "variant-minimal",
            "p_clock": "variant-minimal",
            "p_audio": "variant-banner",
            "p_image": "variant-compact",
        },
    },
    {
        "id": "ice_matrix",
        "name": "Ice Matrix",
        "description": "冷色矩阵风格，强调细线与留白。",
        "screen_profile": "wide",
        "recommended_resolution": "1920x540",
        "layout_class": "layout-wide",
        "theme_class": "theme-ice",
        "font_preset": "ice_thin",
        "style_preset": "ice_flow",
        "global_scale": 1.1,
        "tags": ["matrix", "wide", "cool"],
        "purpose_tags": ["data", "monitoring"],
        "style_tags": ["ice", "matrix"],
        "active_components": ["p_hardware", "p_network", "p_clock", "p_audio", "p_image"],
        "component_variants": {
            "p_hardware": "variant-slim",
            "p_network": "variant-slim",
            "p_clock": "variant-minimal",
            "p_audio": "variant-banner",
            "p_image": "variant-slim",
        },
    },
    {
        "id": "signal_column",
        "name": "Signal Column",
        "description": "细长竖屏专用，组件垂直堆叠。",
        "screen_profile": "portrait",
        "recommended_resolution": "480x1280",
        "layout_class": "layout-portrait",
        "theme_class": "theme-neon",
        "font_preset": "neon_block",
        "style_preset": "neon_core",
        "global_scale": 0.9,
        "tags": ["portrait", "vertical", "stack"],
        "purpose_tags": ["vertical", "status"],
        "style_tags": ["neon", "signal"],
        "active_components": ["p_hardware", "p_network", "p_clock", "p_audio", "p_image"],
        "component_variants": {
            "p_hardware": "variant-dense",
            "p_network": "variant-minimal",
            "p_clock": "variant-minimal",
            "p_audio": "variant-compact",
            "p_image": "variant-compact",
        },
    },
    {
        "id": "tower_radar",
        "name": "Tower Radar",
        "description": "高而窄的纵向屏幕，信息自上而下分区。",
        "screen_profile": "tall",
        "recommended_resolution": "400x1200",
        "layout_class": "layout-tall",
        "theme_class": "theme-ice",
        "font_preset": "ice_thin",
        "style_preset": "ice_flow",
        "global_scale": 0.85,
        "tags": ["portrait", "tall", "scanner"],
        "purpose_tags": ["scanner", "telemetry"],
        "style_tags": ["ice", "matrix"],
        "active_components": ["p_hardware", "p_network", "p_clock", "p_audio", "p_image"],
        "component_variants": {
            "p_hardware": "variant-slim",
            "p_network": "variant-minimal",
            "p_clock": "variant-minimal",
            "p_audio": "variant-compact",
            "p_image": "variant-slim",
        },
    },
    {
        "id": "square_hub",
        "name": "Square Hub",
        "description": "方形小屏多宫格布局，适合 800x800。",
        "screen_profile": "square",
        "recommended_resolution": "800x800",
        "layout_class": "layout-square",
        "theme_class": "theme-amber",
        "font_preset": "amber_ascii",
        "style_preset": "amber_scan",
        "global_scale": 1.0,
        "tags": ["square", "grid", "hub"],
        "purpose_tags": ["hub", "overview"],
        "style_tags": ["retro", "amber"],
        "active_components": ["p_hardware", "p_network", "p_clock", "p_audio", "p_image"],
        "component_variants": {
            "p_hardware": "variant-compact",
            "p_network": "variant-compact",
            "p_clock": "variant-minimal",
            "p_audio": "variant-compact",
            "p_image": "variant-compact",
        },
    },
    {
        "id": "mono_strip",
        "name": "Mono Strip",
        "description": "底部状态条式布局，适合超低高度副屏。",
        "screen_profile": "strip",
        "recommended_resolution": "1920x360",
        "layout_class": "layout-strip",
        "theme_class": "theme-mono",
        "font_preset": "mono_dot",
        "style_preset": "mono_line",
        "global_scale": 0.8,
        "tags": ["strip", "minimal", "status"],
        "purpose_tags": ["status", "minimal"],
        "style_tags": ["mono", "minimal"],
        "active_components": ["p_hardware", "p_network", "p_clock", "p_audio", "p_image"],
        "component_variants": {
            "p_hardware": "variant-minimal",
            "p_network": "variant-minimal",
            "p_clock": "variant-minimal",
            "p_audio": "variant-banner",
            "p_image": "variant-minimal",
        },
    },
    {
        "id": "neon_grid",
        "name": "Neon Grid",
        "description": "高对比网格布局，强调模块边界与层次。",
        "screen_profile": "wide",
        "recommended_resolution": "1600x600",
        "layout_class": "layout-wide",
        "theme_class": "theme-neon",
        "font_preset": "neon_block",
        "style_preset": "neon_core",
        "global_scale": 1.0,
        "tags": ["grid", "cyber", "wide"],
        "purpose_tags": ["dashboard", "monitoring"],
        "style_tags": ["neon", "grid"],
        "active_components": ["p_hardware", "p_network", "p_clock", "p_audio", "p_image"],
        "component_variants": {
            "p_hardware": "variant-dense",
            "p_network": "variant-slim",
            "p_clock": "variant-minimal",
            "p_audio": "variant-banner",
            "p_image": "variant-compact",
        },
    },
    {
        "id": "aurora_command",
        "name": "Aurora Command",
        "description": "极光指挥台，超宽多层信息 + 通道提示。",
        "screen_profile": "ultrawide",
        "recommended_resolution": "2560x720",
        "layout_class": "layout-ultrawide-plus",
        "theme_class": "theme-aurora",
        "font_preset": "ice_thin",
        "style_preset": "aurora_wave",
        "global_scale": 1.05,
        "tags": ["ultrawide", "aurora", "command"],
        "purpose_tags": ["command", "dashboard"],
        "style_tags": ["aurora", "holo"],
        "active_components": ["p_hardware", "p_network", "p_clock", "p_audio", "p_image", "p_ticker", "p_badge"],
        "component_variants": {
            "p_hardware": "variant-dense",
            "p_network": "variant-slim",
            "p_clock": "variant-minimal",
            "p_audio": "variant-banner",
            "p_image": "variant-compact",
            "p_ticker": "variant-outline",
            "p_badge": "variant-compact",
        },
    },
    {
        "id": "vapor_bridge",
        "name": "Vapor Bridge",
        "description": "霓虹蒸汽波桥架，强化信号流与信息条。",
        "screen_profile": "wide",
        "recommended_resolution": "1600x600",
        "layout_class": "layout-wide-plus",
        "theme_class": "theme-vapor",
        "font_preset": "vapor_line",
        "style_preset": "vapor_pulse",
        "global_scale": 0.95,
        "tags": ["wide", "vapor", "stream"],
        "purpose_tags": ["media", "dashboard"],
        "style_tags": ["vapor", "neon"],
        "active_components": ["p_hardware", "p_network", "p_clock", "p_audio", "p_stream", "p_ticker"],
        "component_variants": {
            "p_hardware": "variant-outline",
            "p_network": "variant-slim",
            "p_clock": "variant-minimal",
            "p_audio": "variant-banner",
            "p_stream": "variant-glow",
            "p_ticker": "variant-outline",
        },
    },
    {
        "id": "ember_status",
        "name": "Ember Status",
        "description": "暖色状态条，适合低高度副屏。",
        "screen_profile": "strip",
        "recommended_resolution": "1920x360",
        "layout_class": "layout-strip-plus",
        "theme_class": "theme-ember",
        "font_preset": "amber_ascii",
        "style_preset": "ember_core",
        "global_scale": 0.85,
        "tags": ["strip", "status", "ember"],
        "purpose_tags": ["status", "monitoring"],
        "style_tags": ["ember", "warm"],
        "active_components": ["p_network", "p_clock", "p_ticker", "p_badge"],
        "component_variants": {
            "p_network": "variant-minimal",
            "p_clock": "variant-minimal",
            "p_ticker": "variant-banner",
            "p_badge": "variant-compact",
        },
    },
    {
        "id": "signal_pillar",
        "name": "Signal Pillar",
        "description": "纵向信号塔，突出流式数据与状态徽章。",
        "screen_profile": "portrait",
        "recommended_resolution": "480x1280",
        "layout_class": "layout-portrait-plus",
        "theme_class": "theme-ice",
        "font_preset": "matrix_code",
        "style_preset": "ice_flow",
        "global_scale": 0.9,
        "tags": ["portrait", "signal", "stream"],
        "purpose_tags": ["telemetry", "vertical"],
        "style_tags": ["matrix", "ice"],
        "active_components": ["p_hardware", "p_network", "p_clock", "p_stream", "p_badge"],
        "component_variants": {
            "p_hardware": "variant-slim",
            "p_network": "variant-minimal",
            "p_clock": "variant-minimal",
            "p_stream": "variant-glow",
            "p_badge": "variant-compact",
        },
    },
    {
        "id": "holo_square",
        "name": "Holo Square",
        "description": "方形全息面板，带徽章与主视觉。",
        "screen_profile": "square",
        "recommended_resolution": "800x800",
        "layout_class": "layout-square",
        "theme_class": "theme-vapor",
        "font_preset": "vapor_line",
        "style_preset": "vapor_pulse",
        "global_scale": 1.0,
        "tags": ["square", "holo", "panel"],
        "purpose_tags": ["hub", "display"],
        "style_tags": ["vapor", "holo"],
        "active_components": ["p_hardware", "p_network", "p_clock", "p_image", "p_badge"],
        "component_variants": {
            "p_hardware": "variant-compact",
            "p_network": "variant-minimal",
            "p_clock": "variant-minimal",
            "p_image": "variant-compact",
            "p_badge": "variant-outline",
        },
    },
    {
        "id": "nocturne_grid",
        "name": "Nocturne Grid",
        "description": "深夜数据栅格，低对比冷光。",
        "screen_profile": "wide",
        "recommended_resolution": "1600x600",
        "layout_class": "layout-wide",
        "theme_class": "theme-night",
        "font_preset": "mono_dot",
        "style_preset": "mono_line",
        "global_scale": 0.9,
        "tags": ["wide", "night", "grid"],
        "purpose_tags": ["dashboard", "monitoring"],
        "style_tags": ["mono", "night"],
        "active_components": ["p_hardware", "p_network", "p_clock", "p_image", "p_ticker"],
        "component_variants": {
            "p_hardware": "variant-dense",
            "p_network": "variant-slim",
            "p_clock": "variant-minimal",
            "p_image": "variant-compact",
            "p_ticker": "variant-outline",
        },
    },
]


def list_templates() -> List[Dict[str, object]]:
    return TEMPLATE_PRESETS


def get_template(template_id: Optional[str]) -> Optional[Dict[str, object]]:
    if not template_id:
        return None
    for template in TEMPLATE_PRESETS:
        if template.get("id") == template_id:
            return template
    return None


def get_font_preset(preset_id: Optional[str]) -> Dict[str, object]:
    if not preset_id:
        return FONT_PRESETS[DEFAULT_FONT_PRESET_ID]
    return FONT_PRESETS.get(preset_id, FONT_PRESETS[DEFAULT_FONT_PRESET_ID])


def list_font_presets() -> List[Dict[str, object]]:
    return [{"id": key, "name": value.get("name", key)} for key, value in FONT_PRESETS.items()]


def get_style_preset(preset_id: Optional[str]) -> Dict[str, object]:
    if not preset_id:
        return STYLE_PRESETS[DEFAULT_STYLE_PRESET_ID]
    return STYLE_PRESETS.get(preset_id, STYLE_PRESETS[DEFAULT_STYLE_PRESET_ID])


def list_style_presets() -> List[Dict[str, object]]:
    return [{"id": key, "name": value.get("name", key)} for key, value in STYLE_PRESETS.items()]
